src/Entity/Games.php
<?php

namespace App\Entity;

use App\Repository\GameRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

#[ORM\Entity(repositoryClass: GameRepository::class)]
class Games
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'games')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Tournaments $tournament = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Teams $first_team = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Teams $second_team = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[Gedmo\Timestampable(on:"update")]
    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[Gedmo\Timestampable(on:"update")]
    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $updated_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTournament(): ?Tournaments
    {
        return $this->tournament;
    }

    public function setTournament(?Tournaments $tournament): static
    {
        $this->tournament = $tournament;

        return $this;
    }

    public function getFirstTeam(): ?Teams
    {
        return $this->first_team;
    }

    public function setFirstTeam(?Teams $first_team): static
    {
        $this->first_team = $first_team;

        return $this;
    }

    public function getSecondTeam(): ?Teams
    {
        return $this->second_team;
    }

    public function setSecondTeam(?Teams $second_team): static
    {
        $this->second_team = $second_team;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Entity/Tournaments.php
<?php

namespace App\Entity;

use App\Repository\TournamentsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

#[ORM\Entity(repositoryClass: TournamentsRepository::class)]
#[UniqueEntity('slug')]
class Tournaments
{
    public const ALGORITHMS = [
        'random',
    ];

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 120)]
    private ?string $title = null;

    #[Gedmo\Slug(fields: ["title"])]
    #[ORM\Column(length: 150)]
    private ?string $slug = null;

    #[Gedmo\Timestampable(on:"update")]
    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[Gedmo\Timestampable(on:"update")]
    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $updated_at = null;

    #[ORM\ManyToMany(targetEntity: Teams::class)]
    private Collection $teams;

    #[ORM\OneToMany(mappedBy: 'tournament', targetEntity: Games::class, orphanRemoval: true)]
    private Collection $games;

    public function __construct()
    {
        $this->teams = new ArrayCollection();
        $this->games = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection<int, Teams>
     */
    public function getTeams(): Collection
    {
        return $this->teams;
    }

    public function addTeam(Teams $team): static
    {
        if (!$this->teams->contains($team)) {
            $this->teams->add($team);
        }

        return $this;
    }

    public function removeTeam(Teams $team): static
    {
        $this->teams->removeElement($team);

        return $this;
    }

    /**
     * @return Collection<int, Games>
     */
    public function getGames(): Collection
    {
        return $this->games;
    }

    public function addGame(Games $game): static
    {
        if (!$this->games->contains($game)) {
            $this->games->add($game);
            $game->setTournament($this);
        }

        return $this;
    }

    public function removeGame(Games $game): static
    {
        if ($this->games->removeElement($game)) {
            // set the owning side to null (unless already changed)
            if ($game->getTournament() === $this) {
                $game->setTournament(null);
            }
        }

        return $this;
    }
}

src/Form/TournamentsType.php
<?php

namespace App\Form;

use App\Entity\Teams;
use App\Entity\Tournaments;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TournamentsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title');
        $builder
            ->add('teams', EntityType::class, [
                'class'        => Teams::class,
                'multiple'     => true,
                'expanded'     => true,
                'choice_label' => 'title',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Tournaments::class,
        ]);
    }
}

src/Controller/TournamentsController.php
<?php

namespace App\Controller;

use App\Entity\Tournaments;
use App\Form\TournamentsType;
use App\Handlers\SchedulerClear;
use App\Handlers\SchedulerRandom;
use App\Handlers\SchedulerShow;
use App\Repository\TournamentsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/tournaments')]
class TournamentsController extends AbstractController
{
    public function __construct(
        private SchedulerRandom $schedulerRandom,
        private SchedulerClear $schedulerClear
    ) {
    }

    #[Route('/', name: 'app_tournaments_index', methods: ['GET'])]
    public function index(TournamentsRepository $tournamentsRepository): Response
    {
        return $this->render('tournaments/index.html.twig', [
            'tournaments' => $tournamentsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_tournaments_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $tournament = new Tournaments();
        $form = $this->createForm(TournamentsType::class, $tournament);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($tournament);
            $entityManager->flush();

            $this->schedulerRandom->create($tournament, $entityManager);

            return $this->redirectToRoute('app_tournaments_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('tournaments/new.html.twig', [
            'tournament' => $tournament,
            'form' => $form,
        ]);
    }

    #[Route('/{slug}', name: 'app_tournaments_show', methods: ['GET'])]
    public function show(Tournaments $tournament, SchedulerShow $scheduler): Response
    {
        return $this->render('tournaments/show.html.twig', [
            'tournament' => $tournament,
            'games' => $scheduler->getGrid($tournament),
        ]);
    }

    #[Route('/{slug}/edit', name: 'app_tournaments_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Tournaments $tournament, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(TournamentsType::class, $tournament);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            $this->schedulerClear->clear($tournament, $entityManager);
            $this->schedulerRandom->create($tournament, $entityManager);

            return $this->redirectToRoute('app_tournaments_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('tournaments/edit.html.twig', [
            'tournament' => $tournament,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_tournaments_delete', methods: ['POST'])]
    public function delete(Request $request, Tournaments $tournament, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$tournament->getId(), $request->request->get('_token'))) {
            $entityManager->remove($tournament);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_tournaments_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/tournaments/_delete_form.html.twig
<form method="post" action="{{ path('app_tournaments_delete', {'id': tournament.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tournament.id) }}">
    <button class="btn">Delete</button>
</form>

templates/tournaments/_form.html.twig
{{ form_start(form) }}
    <div class="form-group">
        {{ form_row(form.title, {'attr': {'class': 'form-control'}}) }}
    </div>
    <div class="form-group">
        {% for team in form.teams %}
            <div class="form-group">
                {{ form_row(team) }}
            </div>
        {% endfor %}
    </div>
    <button class="btn {{ button_color|default('btn-outline-primary') }}  mt-3">{{ button_label|default('Save Tournament') }}</button>
{{ form_end(form) }}

templates/tournaments/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Tournaments{% endblock %}

{% block body %}
    <div class="container">
        <h2 class="text-center mt-5 mb-3">Edit Tournaments</h2>
        <div class="card">
            <div class="card-header">
                <a class="btn btn-outline-info float-right" href="{{ path('app_tournaments_index') }}">
                    View All Tournaments
                </a>
            </div>
            <div class="card-body">
                {% include 'tournaments/_form.html.twig' with {'button_label': 'Update Tournament', 'button_color': 'btn-outline-success'}  %}
            </div>
        </div>
    </div>
{% endblock %}

templates/tournaments/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tournaments index{% endblock %}

{% block body %}
<div class="container">
    <h2 class="text-center mt-5 mb-3">Tournaments Manager</h2>
    <div class="card">
        <div class="card-header">
            <a class="btn btn-outline-primary" href="{{ path('app_tournaments_new') }}">
                Create new
            </a>
        </div>
        <div class="card-body">
            <table class="table table-bordered">
                <tr>
                    <th>Name</th>
                    <th>Date Created</th>
                    <th>Date Updated</th>
                    <th width="240px">Action</th>
                </tr>
                {% for tournament in tournaments %}
                    <tr>
                        <td>{{ tournament.title }}</td>
                        <td>{{ tournament.createdAt ? tournament.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                        <td>{{ tournament.updatedAt ? tournament.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                        <td>
                            <form method="post" action="{{ path('app_tournaments_delete', {'id': tournament.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                                <a
                                        class="btn btn-outline-info"
                                        href="{{ path('app_tournaments_show', {'slug': tournament.slug}) }}">
                                    Show
                                </a>
                                <a
                                        class="btn btn-outline-success"
                                        href="{{ path('app_tournaments_edit', {'slug': tournament.slug}) }}">
                                    Edit
                                </a>

                                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tournament.id) }}">
                                <button class="btn btn-outline-danger">Delete</button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/tournaments/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Tournaments{% endblock %}

{% block body %}
    <div class="container">
        <h2 class="text-center mt-5 mb-3">Create Tournaments</h2>
        <div class="card">
            <div class="card-header">
                <a class="btn btn-outline-info float-right" href="{{ path('app_tournaments_index') }}">
                    View All Teams
                </a>
            </div>
            <div class="card-body">
                {{ include('tournaments/_form.html.twig') }}
            </div>
        </div>
    </div>
{% endblock %}

templates/tournaments/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tournaments{% endblock %}

{% block body %}
    <div class="container">
        <h2 class="text-center mt-5 mb-3">Show Tournament</h2>
        <div class="card">
            <div class="card-header">
                <a class="btn btn-outline-info float-right" href="{{ path('app_tournaments_index') }}">
                    View All Tournaments
                </a>
            </div>
            <div class="card-body">
                <h2 class="text-center mt-5 mb-3">{{ tournament.title }}</h2>

                <div class="row">
                    {% for date, gameDay in games %}
                        <div class="game-day-block row">
                            <div class="date-field text-center">
                                {{ date }}
                            </div>
                            <div class="game-day">
                                {% for game in gameDay %}
                                    <div class="row">
                                        <div class="text-right col-6">
                                            {{ game.firstTeam.title }}
                                        </div>
                                        <div class="text-left col-6">
                                            {{ game.secondTeam.title }}
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}